on:
  [push]

jobs:
  check_job:
    runs-on: ubuntu-latest
    name: A job to checkout
    steps:
    - name: action
      id: wen
      uses: WhenWen/myaction@v6
    - name: output
      run: echo "These are some suggestions.${{ steps.wen.outputs.suggestion }} "
